import {
    ArrowDownIcon,
    ArrowUpIcon,
    Check,
    CheckCircle,
    ChevronLeft,
    ChevronRight,
    Clock,
    CreditCard,
    Edit,
    Eye,
    EyeOff,
    FileText,
    HelpCircle,
    Home,
    Loader2,
    Lock,
    LogOut,
    Mail,
    Menu,
    Plus,
    Settings,
    Trash2,
    UserPlus,
    Users,
    X,
    XCircle,
    AlertTriangle,
    AlertCircle,
    CalendarIcon,
    FilterIcon,
  } from "lucide-react"
  
  export const Icons = {
    spinner: Loader2,
    check: Check,
    creditCard: CreditCard,
    mail: Mail,
    lock: Lock,
    arrowUp: ArrowUpIcon,
    arrowDown: ArrowDownIcon,
    fileText: FileText,
    x: X,
    checkCircle: CheckCircle,
    clock: Clock,
    alertCircle: AlertCircle,
    plus: Plus,
    userPlus: UserPlus,
    edit: Edit,
    eye: Eye,
    eyeOff: EyeOff,
    trash2: Trash2,
    calendar: CalendarIcon,
    filter: FilterIcon,
    xCircle: XCircle,
    alertTriangle: AlertTriangle,
    home: Home,
    users: Users,
    settings: Settings,
    logOut: LogOut,
    helpCircle: HelpCircle,
    menu: Menu,
    chevronRight: ChevronRight,
    chevronLeft: ChevronLeft,
  }
  